# Generated by Django 3.2.4 on 2021-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=200)),
                ('q2', models.CharField(max_length=200)),
                ('q3', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=100)),
            ],
        ),
    ]
