# Generated by Django 3.2.4 on 2021-08-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodam', '0002_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='images',
        ),
        migrations.AddField(
            model_name='picture',
            name='draw',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
